### ISSUE TITLE
1.7.10 creation of map

### ISSUE THREAD

**Issue by SvEgiiVEteR** [TheRandomLabs/Default-Gamerules#1]
https://gist.github.com/5bdaddd35c4b52953cdc67e515af6882
after creating crash
1.0.1 also

**Comment by Kf4btg** [comment]
Exact same error on 1.11.  Looks like maybe the default config file isn't being created?

**Comment by SvEgiiVEteR** [comment]
Yes that's right. I think the same.

**Comment by TheRandomLabs** [comment]
Strange, I didn't get this error, and I've tested on several clients and servers. I think I might know what the problem is though.

**Comment by TheRandomLabs** [comment]
I've uploaded the new version - it should be available soon. Tell me if it works.

**Comment by SvEgiiVEteR** [comment]
all is well, the config created. the rules work
